platform:ios,'8.0'
pod ‘AFNetworking‘, ‘~> 2.6’
pod ‘MJRefresh’
pod ‘MJExtension’
pod ‘SDWebImage’
pod ‘Masonry’
pod ‘SDCycleScrollView’
pod 'SVProgressHUD'
pod 'IQKeyboardManager'

pod 'AVOSCloud'
pod 'AVOSCloudIM'
